# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geoElectre.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(687, 598)
        Dialog.setMaximumSize(QtCore.QSize(694, 700))
        font = QtGui.QFont()
        font.setPointSize(6)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(True)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet("\n"
"font: 75 italic 10pt \"MS Shell Dlg 2\";")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.EnvironmentaleQTbox = QtWidgets.QWidget()
        self.EnvironmentaleQTbox.setGeometry(QtCore.QRect(0, 0, 669, 520))
        self.EnvironmentaleQTbox.setObjectName("EnvironmentaleQTbox")
        self.EnvlistFieldsCBox = QtWidgets.QComboBox(self.EnvironmentaleQTbox)
        self.EnvlistFieldsCBox.setGeometry(QtCore.QRect(88, 62, 421, 22))
        self.EnvlistFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.EnvlistFieldsCBox.setObjectName("EnvlistFieldsCBox")
        self.EnvLbl = QtWidgets.QLabel(self.EnvironmentaleQTbox)
        self.EnvLbl.setGeometry(QtCore.QRect(9, 9, 51, 16))
        self.EnvLbl.setObjectName("EnvLbl")
        self.EnvMapNameLbl = QtWidgets.QLabel(self.EnvironmentaleQTbox)
        self.EnvMapNameLbl.setGeometry(QtCore.QRect(69, 8, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.EnvMapNameLbl.setFont(font)
        self.EnvMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.EnvMapNameLbl.setObjectName("EnvMapNameLbl")
        self.EnvTEdit = QtWidgets.QTextEdit(self.EnvironmentaleQTbox)
        self.EnvTEdit.setGeometry(QtCore.QRect(10, 420, 530, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.EnvTEdit.sizePolicy().hasHeightForWidth())
        self.EnvTEdit.setSizePolicy(sizePolicy)
        self.EnvTEdit.setObjectName("EnvTEdit")
        self.EnvFieldsLbl = QtWidgets.QLabel(self.EnvironmentaleQTbox)
        self.EnvFieldsLbl.setGeometry(QtCore.QRect(9, 62, 34, 16))
        self.EnvFieldsLbl.setObjectName("EnvFieldsLbl")
        self.SetBtnHelp = QtWidgets.QPushButton(self.EnvironmentaleQTbox)
        self.SetBtnHelp.setGeometry(QtCore.QRect(560, 450, 102, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetBtnHelp.sizePolicy().hasHeightForWidth())
        self.SetBtnHelp.setSizePolicy(sizePolicy)
        self.SetBtnHelp.setMaximumSize(QtCore.QSize(110, 16777215))
        self.SetBtnHelp.setObjectName("SetBtnHelp")
        self.line_2 = QtWidgets.QFrame(self.EnvironmentaleQTbox)
        self.line_2.setGeometry(QtCore.QRect(9, 36, 657, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.EnvironmentaleQTbox)
        self.line_4.setGeometry(QtCore.QRect(10, 390, 660, 15))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.EnvTabWidget = QtWidgets.QTabWidget(self.EnvironmentaleQTbox)
        self.EnvTabWidget.setGeometry(QtCore.QRect(14, 105, 651, 301))
        self.EnvTabWidget.setObjectName("EnvTabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.EnvParameterWidget = QtWidgets.QTableWidget(self.tab_5)
        self.EnvParameterWidget.setGeometry(QtCore.QRect(10, 21, 630, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvParameterWidget.sizePolicy().hasHeightForWidth())
        self.EnvParameterWidget.setSizePolicy(sizePolicy)
        self.EnvParameterWidget.setAcceptDrops(False)
        self.EnvParameterWidget.setAutoFillBackground(True)
        self.EnvParameterWidget.setDragEnabled(True)
        self.EnvParameterWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.EnvParameterWidget.setShowGrid(True)
        self.EnvParameterWidget.setGridStyle(QtCore.Qt.DotLine)
        self.EnvParameterWidget.setRowCount(0)
        self.EnvParameterWidget.setObjectName("EnvParameterWidget")
        self.EnvParameterWidget.setColumnCount(0)
        self.EnvParameterWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.EnvParameterWidget.verticalHeader().setCascadingSectionResizes(False)
        self.EnvParameterWidget.verticalHeader().setHighlightSections(True)
        self.EnvGetWeightBtn = QtWidgets.QPushButton(self.tab_5)
        self.EnvGetWeightBtn.setGeometry(QtCore.QRect(540, 190, 104, 24))
        self.EnvGetWeightBtn.setMaximumSize(QtCore.QSize(104, 16777215))
        self.EnvGetWeightBtn.setObjectName("EnvGetWeightBtn")
        self.EnvProgressBar = QtWidgets.QProgressBar(self.tab_5)
        self.EnvProgressBar.setGeometry(QtCore.QRect(10, 190, 521, 25))
        self.EnvProgressBar.setProperty("value", 0)
        self.EnvProgressBar.setObjectName("EnvProgressBar")
        self.EnvTabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.EnvCalculateBtn = QtWidgets.QPushButton(self.tab_6)
        self.EnvCalculateBtn.setGeometry(QtCore.QRect(530, 240, 111, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvCalculateBtn.sizePolicy().hasHeightForWidth())
        self.EnvCalculateBtn.setSizePolicy(sizePolicy)
        self.EnvCalculateBtn.setMaximumSize(QtCore.QSize(111, 16777215))
        self.EnvCalculateBtn.setObjectName("EnvCalculateBtn")
        self.EnvTableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.EnvTableWidget.setEnabled(True)
        self.EnvTableWidget.setGeometry(QtCore.QRect(10, 15, 630, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvTableWidget.sizePolicy().hasHeightForWidth())
        self.EnvTableWidget.setSizePolicy(sizePolicy)
        self.EnvTableWidget.setDragEnabled(True)
        self.EnvTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.EnvTableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.EnvTableWidget.setObjectName("EnvTableWidget")
        self.EnvTableWidget.setColumnCount(0)
        self.EnvTableWidget.setRowCount(0)
        self.EnvTabWidget.addTab(self.tab_6, "")
        self.EnvAddFieldBtn = QtWidgets.QPushButton(self.EnvironmentaleQTbox)
        self.EnvAddFieldBtn.setGeometry(QtCore.QRect(551, 62, 111, 24))
        self.EnvAddFieldBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.EnvAddFieldBtn.setObjectName("EnvAddFieldBtn")
        self.SetBtnAbout = QtWidgets.QPushButton(self.EnvironmentaleQTbox)
        self.SetBtnAbout.setGeometry(QtCore.QRect(560, 480, 102, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetBtnAbout.sizePolicy().hasHeightForWidth())
        self.SetBtnAbout.setSizePolicy(sizePolicy)
        self.SetBtnAbout.setMaximumSize(QtCore.QSize(110, 16777215))
        self.SetBtnAbout.setObjectName("SetBtnAbout")
        self.SetBtnQuit = QtWidgets.QPushButton(self.EnvironmentaleQTbox)
        self.SetBtnQuit.setGeometry(QtCore.QRect(560, 420, 102, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetBtnQuit.sizePolicy().hasHeightForWidth())
        self.SetBtnQuit.setSizePolicy(sizePolicy)
        self.SetBtnQuit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.SetBtnQuit.setObjectName("SetBtnQuit")
        self.EnvAddFieldBtn.raise_()
        self.EnvlistFieldsCBox.raise_()
        self.EnvLbl.raise_()
        self.EnvMapNameLbl.raise_()
        self.EnvTEdit.raise_()
        self.EnvFieldsLbl.raise_()
        self.SetBtnHelp.raise_()
        self.line_2.raise_()
        self.line_4.raise_()
        self.EnvTabWidget.raise_()
        self.SetBtnAbout.raise_()
        self.SetBtnQuit.raise_()
        self.toolBox.addItem(self.EnvironmentaleQTbox, "")
        self.AnalysisQTBox = QtWidgets.QWidget()
        self.AnalysisQTBox.setGeometry(QtCore.QRect(0, 0, 669, 520))
        self.AnalysisQTBox.setObjectName("AnalysisQTBox")
        self.GraphBtn = QtWidgets.QPushButton(self.AnalysisQTBox)
        self.GraphBtn.setGeometry(QtCore.QRect(567, 73, 75, 23))
        self.GraphBtn.setObjectName("GraphBtn")
        self.LblGraphic = QtWidgets.QLabel(self.AnalysisQTBox)
        self.LblGraphic.setGeometry(QtCore.QRect(21, 122, 518, 251))
        self.LblGraphic.setAutoFillBackground(False)
        self.LblGraphic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LblGraphic.setText("")
        self.LblGraphic.setScaledContents(True)
        self.LblGraphic.setObjectName("LblGraphic")
        self.RenderBtn = QtWidgets.QPushButton(self.AnalysisQTBox)
        self.RenderBtn.setGeometry(QtCore.QRect(565, 19, 75, 23))
        self.RenderBtn.setObjectName("RenderBtn")
        self.line = QtWidgets.QFrame(self.AnalysisQTBox)
        self.line.setGeometry(QtCore.QRect(14, 49, 644, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.LabelListFieldsCBox = QtWidgets.QComboBox(self.AnalysisQTBox)
        self.LabelListFieldsCBox.setGeometry(QtCore.QRect(114, 76, 419, 22))
        self.LabelListFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.LabelListFieldsCBox.setObjectName("LabelListFieldsCBox")
        self.label_3 = QtWidgets.QLabel(self.AnalysisQTBox)
        self.label_3.setGeometry(QtCore.QRect(29, 78, 64, 16))
        self.label_3.setObjectName("label_3")
        self.AnlsBtnBox = QtWidgets.QDialogButtonBox(self.AnalysisQTBox)
        self.AnlsBtnBox.setGeometry(QtCore.QRect(560, 350, 86, 23))
        self.AnlsBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.AnlsBtnBox.setObjectName("AnlsBtnBox")
        self.label_4 = QtWidgets.QLabel(self.AnalysisQTBox)
        self.label_4.setGeometry(QtCore.QRect(30, 19, 151, 21))
        self.label_4.setObjectName("label_4")
        self.spinBoxClasNum = QtWidgets.QSpinBox(self.AnalysisQTBox)
        self.spinBoxClasNum.setGeometry(QtCore.QRect(380, 20, 42, 22))
        self.spinBoxClasNum.setProperty("value", 5)
        self.spinBoxClasNum.setObjectName("spinBoxClasNum")
        self.label_7 = QtWidgets.QLabel(self.AnalysisQTBox)
        self.label_7.setGeometry(QtCore.QRect(250, 20, 111, 20))
        self.label_7.setObjectName("label_7")
        self.toolBox.addItem(self.AnalysisQTBox, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        self.EnvTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.EnvAddFieldBtn, self.EnvTEdit)
        Dialog.setTabOrder(self.EnvTEdit, self.GraphBtn)
        Dialog.setTabOrder(self.GraphBtn, self.SetBtnHelp)
        Dialog.setTabOrder(self.SetBtnHelp, self.EnvlistFieldsCBox)
        Dialog.setTabOrder(self.EnvlistFieldsCBox, self.RenderBtn)
        Dialog.setTabOrder(self.RenderBtn, self.LabelListFieldsCBox)
        Dialog.setTabOrder(self.LabelListFieldsCBox, self.AnlsBtnBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "geoConcordance"))
        self.EnvLbl.setText(_translate("Dialog", "Layer     "))
        self.EnvFieldsLbl.setText(_translate("Dialog", "Fields"))
        self.SetBtnHelp.setText(_translate("Dialog", "Help"))
        self.EnvGetWeightBtn.setText(_translate("Dialog", "Apply"))
        self.EnvTabWidget.setTabText(self.EnvTabWidget.indexOf(self.tab_5), _translate("Dialog", "Standard"))
        self.EnvCalculateBtn.setText(_translate("Dialog", "Calculate weight"))
        self.EnvTabWidget.setTabText(self.EnvTabWidget.indexOf(self.tab_6), _translate("Dialog", "Advanced"))
        self.EnvAddFieldBtn.setText(_translate("Dialog", "Add"))
        self.SetBtnAbout.setText(_translate("Dialog", "About"))
        self.SetBtnQuit.setText(_translate("Dialog", "Quit"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.EnvironmentaleQTbox), _translate("Dialog", "Criteria"))
        self.GraphBtn.setText(_translate("Dialog", "Graph"))
        self.RenderBtn.setText(_translate("Dialog", "Maps"))
        self.label_3.setText(_translate("Dialog", "Label field"))
        self.label_4.setText(_translate("Dialog", "Load thematic maps"))
        self.label_7.setText(_translate("Dialog", "Classes in maps"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.AnalysisQTBox), _translate("Dialog", "Analysis"))

