# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geoXMCDA.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(607, 586)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setStyleSheet("\n"
"font: 75 italic 10pt \"MS Shell Dlg 2\";")
        self.toolBox.setObjectName("toolBox")
        self.CriteriaQTbox = QtWidgets.QWidget()
        self.CriteriaQTbox.setGeometry(QtCore.QRect(0, 0, 589, 538))
        self.CriteriaQTbox.setObjectName("CriteriaQTbox")
        self.CritListFieldsCBox = QtWidgets.QComboBox(self.CriteriaQTbox)
        self.CritListFieldsCBox.setGeometry(QtCore.QRect(90, 123, 181, 20))
        self.CritListFieldsCBox.setObjectName("CritListFieldsCBox")
        self.EnvLbl = QtWidgets.QLabel(self.CriteriaQTbox)
        self.EnvLbl.setGeometry(QtCore.QRect(10, 0, 111, 19))
        self.EnvLbl.setObjectName("EnvLbl")
        self.CritFieldsLbl = QtWidgets.QLabel(self.CriteriaQTbox)
        self.CritFieldsLbl.setGeometry(QtCore.QRect(2, 122, 81, 23))
        self.CritFieldsLbl.setObjectName("CritFieldsLbl")
        self.CritMapNameLbl = QtWidgets.QLabel(self.CriteriaQTbox)
        self.CritMapNameLbl.setGeometry(QtCore.QRect(100, 0, 361, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.CritMapNameLbl.setFont(font)
        self.CritMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.CritMapNameLbl.setObjectName("CritMapNameLbl")
        self.CritWeighTableWidget = QtWidgets.QTableWidget(self.CriteriaQTbox)
        self.CritWeighTableWidget.setGeometry(QtCore.QRect(20, 200, 311, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CritWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.CritWeighTableWidget.setSizePolicy(sizePolicy)
        self.CritWeighTableWidget.setDragEnabled(True)
        self.CritWeighTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.CritWeighTableWidget.setAlternatingRowColors(True)
        self.CritWeighTableWidget.setRowCount(0)
        self.CritWeighTableWidget.setObjectName("CritWeighTableWidget")
        self.CritWeighTableWidget.setColumnCount(0)
        self.CritWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.CritWeighTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.CritWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.CritRemoveFieldBtn = QtWidgets.QPushButton(self.CriteriaQTbox)
        self.CritRemoveFieldBtn.setGeometry(QtCore.QRect(380, 120, 75, 24))
        self.CritRemoveFieldBtn.setObjectName("CritRemoveFieldBtn")
        self.CritExtractBtn = QtWidgets.QPushButton(self.CriteriaQTbox)
        self.CritExtractBtn.setGeometry(QtCore.QRect(350, 200, 101, 251))
        self.CritExtractBtn.setObjectName("CritExtractBtn")
        self.SetHelpBtn = QtWidgets.QPushButton(self.CriteriaQTbox)
        self.SetHelpBtn.setGeometry(QtCore.QRect(280, 510, 75, 24))
        self.SetHelpBtn.setObjectName("SetHelpBtn")
        self.CritAddFieldBtn = QtWidgets.QPushButton(self.CriteriaQTbox)
        self.CritAddFieldBtn.setGeometry(QtCore.QRect(290, 120, 75, 24))
        self.CritAddFieldBtn.setObjectName("CritAddFieldBtn")
        self.toXMXCDAButtonBox = QtWidgets.QDialogButtonBox(self.CriteriaQTbox)
        self.toXMXCDAButtonBox.setGeometry(QtCore.QRect(365, 510, 91, 24))
        self.toXMXCDAButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.toXMXCDAButtonBox.setObjectName("toXMXCDAButtonBox")
        self.groupBox = QtWidgets.QGroupBox(self.CriteriaQTbox)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 461, 61))
        self.groupBox.setObjectName("groupBox")
        self.btnOutput = QtWidgets.QToolButton(self.groupBox)
        self.btnOutput.setGeometry(QtCore.QRect(16, 20, 61, 25))
        self.btnOutput.setMinimumSize(QtCore.QSize(0, 25))
        self.btnOutput.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btnOutput.setObjectName("btnOutput")
        self.lineOutput = QtWidgets.QLineEdit(self.groupBox)
        self.lineOutput.setGeometry(QtCore.QRect(100, 20, 351, 25))
        self.lineOutput.setObjectName("lineOutput")
        self.IDFieldsLbl = QtWidgets.QLabel(self.CriteriaQTbox)
        self.IDFieldsLbl.setGeometry(QtCore.QRect(12, 460, 81, 23))
        self.IDFieldsLbl.setObjectName("IDFieldsLbl")
        self.IDListFieldsCBox = QtWidgets.QComboBox(self.CriteriaQTbox)
        self.IDListFieldsCBox.setGeometry(QtCore.QRect(80, 461, 271, 20))
        self.IDListFieldsCBox.setObjectName("IDListFieldsCBox")
        self.toolBox.addItem(self.CriteriaQTbox, "")
        self.gridLayout.addWidget(self.toolBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.CritListFieldsCBox, self.CritAddFieldBtn)
        Dialog.setTabOrder(self.CritAddFieldBtn, self.CritRemoveFieldBtn)
        Dialog.setTabOrder(self.CritRemoveFieldBtn, self.CritWeighTableWidget)
        Dialog.setTabOrder(self.CritWeighTableWidget, self.CritExtractBtn)
        Dialog.setTabOrder(self.CritExtractBtn, self.SetHelpBtn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "geoXMCDA"))
        self.EnvLbl.setText(_translate("Dialog", "Active layer     "))
        self.CritFieldsLbl.setText(_translate("Dialog", "Active field"))
        self.CritRemoveFieldBtn.setText(_translate("Dialog", "Remove"))
        self.CritExtractBtn.setText(_translate("Dialog", "--> XMCDA file"))
        self.SetHelpBtn.setText(_translate("Dialog", "Help"))
        self.CritAddFieldBtn.setText(_translate("Dialog", "Add"))
        self.groupBox.setTitle(_translate("Dialog", "Output xmcda file"))
        self.btnOutput.setText(_translate("Dialog", "..."))
        self.IDFieldsLbl.setText(_translate("Dialog", "ID  field"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.CriteriaQTbox), _translate("Dialog", "Table to XMCDA"))

