# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geoRULES.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(518, 570)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setStyleSheet("\n"
"font: 75 italic 10pt \"MS Shell Dlg 2\";")
        self.toolBox.setObjectName("toolBox")
        self.CriteriaQTbox = QtWidgets.QWidget()
        self.CriteriaQTbox.setGeometry(QtCore.QRect(0, 0, 500, 462))
        self.CriteriaQTbox.setObjectName("CriteriaQTbox")
        self.CritListFieldsCBox = QtWidgets.QComboBox(self.CriteriaQTbox)
        self.CritListFieldsCBox.setGeometry(QtCore.QRect(80, 30, 181, 20))
        self.CritListFieldsCBox.setObjectName("CritListFieldsCBox")
        self.EnvLbl = QtWidgets.QLabel(self.CriteriaQTbox)
        self.EnvLbl.setGeometry(QtCore.QRect(2, 0, 71, 19))
        self.EnvLbl.setObjectName("EnvLbl")
        self.CritFieldsLbl = QtWidgets.QLabel(self.CriteriaQTbox)
        self.CritFieldsLbl.setGeometry(QtCore.QRect(2, 32, 81, 23))
        self.CritFieldsLbl.setObjectName("CritFieldsLbl")
        self.CritMapNameLbl = QtWidgets.QLabel(self.CriteriaQTbox)
        self.CritMapNameLbl.setGeometry(QtCore.QRect(100, 0, 361, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.CritMapNameLbl.setFont(font)
        self.CritMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.CritMapNameLbl.setObjectName("CritMapNameLbl")
        self.DeclistFieldsCBox = QtWidgets.QComboBox(self.CriteriaQTbox)
        self.DeclistFieldsCBox.setGeometry(QtCore.QRect(110, 381, 351, 20))
        self.DeclistFieldsCBox.setObjectName("DeclistFieldsCBox")
        self.DecFieldsLbl = QtWidgets.QLabel(self.CriteriaQTbox)
        self.DecFieldsLbl.setGeometry(QtCore.QRect(10, 380, 81, 23))
        self.DecFieldsLbl.setObjectName("DecFieldsLbl")
        self.CritExtractBtn = QtWidgets.QPushButton(self.CriteriaQTbox)
        self.CritExtractBtn.setGeometry(QtCore.QRect(390, 80, 75, 231))
        self.CritExtractBtn.setObjectName("CritExtractBtn")
        self.CritHelpBtn = QtWidgets.QPushButton(self.CriteriaQTbox)
        self.CritHelpBtn.setGeometry(QtCore.QRect(390, 330, 75, 24))
        self.CritHelpBtn.setObjectName("CritHelpBtn")
        self.CritAddFieldBtn = QtWidgets.QPushButton(self.CriteriaQTbox)
        self.CritAddFieldBtn.setGeometry(QtCore.QRect(290, 30, 71, 24))
        self.CritAddFieldBtn.setObjectName("CritAddFieldBtn")
        self.critTableWiget = QtWidgets.QTableWidget(self.CriteriaQTbox)
        self.critTableWiget.setGeometry(QtCore.QRect(0, 70, 371, 291))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.critTableWiget.setFont(font)
        self.critTableWiget.setAutoFillBackground(False)
        self.critTableWiget.setAlternatingRowColors(True)
        self.critTableWiget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.critTableWiget.setShowGrid(False)
        self.critTableWiget.setObjectName("critTableWiget")
        self.critTableWiget.setColumnCount(0)
        self.critTableWiget.setRowCount(0)
        self.toolBox.addItem(self.CriteriaQTbox, "")
        self.RoulesQTBox = QtWidgets.QWidget()
        self.RoulesQTBox.setGeometry(QtCore.QRect(0, 0, 500, 462))
        self.RoulesQTBox.setObjectName("RoulesQTBox")
        self.RulesListWidget = QtWidgets.QListWidget(self.RoulesQTBox)
        self.RulesListWidget.setGeometry(QtCore.QRect(20, 21, 461, 361))
        self.RulesListWidget.setAcceptDrops(True)
        self.RulesListWidget.setObjectName("RulesListWidget")
        self.reclassButtonBox = QtWidgets.QDialogButtonBox(self.RoulesQTBox)
        self.reclassButtonBox.setGeometry(QtCore.QRect(350, 400, 131, 23))
        self.reclassButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.reclassButtonBox.setObjectName("reclassButtonBox")
        self.applyRulesBtn = QtWidgets.QPushButton(self.RoulesQTBox)
        self.applyRulesBtn.setGeometry(QtCore.QRect(20, 400, 161, 23))
        self.applyRulesBtn.setObjectName("applyRulesBtn")
        self.typeRuleCmBox = QtWidgets.QComboBox(self.RoulesQTBox)
        self.typeRuleCmBox.setGeometry(QtCore.QRect(190, 400, 101, 22))
        self.typeRuleCmBox.setObjectName("typeRuleCmBox")
        self.toolBox.addItem(self.RoulesQTBox, "")
        self.settingQTbox = QtWidgets.QWidget()
        self.settingQTbox.setGeometry(QtCore.QRect(0, 0, 500, 462))
        self.settingQTbox.setObjectName("settingQTbox")
        self.SettingButtonBox = QtWidgets.QDialogButtonBox(self.settingQTbox)
        self.SettingButtonBox.setGeometry(QtCore.QRect(330, 390, 156, 24))
        self.SettingButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.SettingButtonBox.setObjectName("SettingButtonBox")
        self.DiscretizeGbox = QtWidgets.QGroupBox(self.settingQTbox)
        self.DiscretizeGbox.setGeometry(QtCore.QRect(10, 230, 471, 131))
        self.DiscretizeGbox.setObjectName("DiscretizeGbox")
        self.spinClasseNum = QtWidgets.QSpinBox(self.DiscretizeGbox)
        self.spinClasseNum.setEnabled(False)
        self.spinClasseNum.setGeometry(QtCore.QRect(60, 41, 36, 22))
        self.spinClasseNum.setMaximum(15)
        self.spinClasseNum.setProperty("value", 5)
        self.spinClasseNum.setObjectName("spinClasseNum")
        self.ClassNumbLbl = QtWidgets.QLabel(self.DiscretizeGbox)
        self.ClassNumbLbl.setGeometry(QtCore.QRect(10, 41, 51, 16))
        self.ClassNumbLbl.setObjectName("ClassNumbLbl")
        self.NewFieldNameDiscLbl = QtWidgets.QLabel(self.DiscretizeGbox)
        self.NewFieldNameDiscLbl.setGeometry(QtCore.QRect(140, 40, 151, 16))
        self.NewFieldNameDiscLbl.setObjectName("NewFieldNameDiscLbl")
        self.cobBoxFieldNameDisc = QtWidgets.QComboBox(self.DiscretizeGbox)
        self.cobBoxFieldNameDisc.setGeometry(QtCore.QRect(290, 40, 171, 22))
        self.cobBoxFieldNameDisc.setObjectName("cobBoxFieldNameDisc")
        self.EnvLbl_2 = QtWidgets.QLabel(self.settingQTbox)
        self.EnvLbl_2.setGeometry(QtCore.QRect(10, 20, 71, 19))
        self.EnvLbl_2.setObjectName("EnvLbl_2")
        self.CritMapNameLbl_2 = QtWidgets.QLabel(self.settingQTbox)
        self.CritMapNameLbl_2.setGeometry(QtCore.QRect(110, 20, 361, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.CritMapNameLbl_2.setFont(font)
        self.CritMapNameLbl_2.setTextFormat(QtCore.Qt.AutoText)
        self.CritMapNameLbl_2.setObjectName("CritMapNameLbl_2")
        self.groupBox = QtWidgets.QGroupBox(self.settingQTbox)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 471, 131))
        self.groupBox.setObjectName("groupBox")
        self.checkSelected = QtWidgets.QCheckBox(self.groupBox)
        self.checkSelected.setGeometry(QtCore.QRect(20, 60, 331, 17))
        self.checkSelected.setObjectName("checkSelected")
        self.toolBox.addItem(self.settingQTbox, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.CritListFieldsCBox, self.CritAddFieldBtn)
        Dialog.setTabOrder(self.CritAddFieldBtn, self.CritExtractBtn)
        Dialog.setTabOrder(self.CritExtractBtn, self.CritHelpBtn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "geoRules"))
        self.EnvLbl.setText(_translate("Dialog", "Active layer     "))
        self.CritFieldsLbl.setText(_translate("Dialog", "Active field"))
        self.DecFieldsLbl.setText(_translate("Dialog", "Decision field"))
        self.CritExtractBtn.setText(_translate("Dialog", " Extract"))
        self.CritHelpBtn.setText(_translate("Dialog", "Help"))
        self.CritAddFieldBtn.setText(_translate("Dialog", "Add"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.CriteriaQTbox), _translate("Dialog", "Criteria"))
        self.applyRulesBtn.setText(_translate("Dialog", "Apply rules to maps"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.RoulesQTBox), _translate("Dialog", "Rules"))
        self.DiscretizeGbox.setTitle(_translate("Dialog", "Discretize"))
        self.ClassNumbLbl.setText(_translate("Dialog", "Classes"))
        self.NewFieldNameDiscLbl.setText(_translate("Dialog", "Classification field name"))
        self.EnvLbl_2.setText(_translate("Dialog", "Active layer     "))
        self.groupBox.setTitle(_translate("Dialog", "Features to use"))
        self.checkSelected.setText(_translate("Dialog", "Use  selected features only"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.settingQTbox), _translate("Dialog", "Setting"))

