# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\geoElectre.ui'
#
# Created: Wed Jan 21 23:35:14 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(694, 595)
        Dialog.setMaximumSize(QtCore.QSize(694, 700))
        font = QtGui.QFont()
        font.setPointSize(6)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(True)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolBox = QtGui.QToolBox(Dialog)
        self.toolBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet(_fromUtf8("\n"
"font: 75 italic 10pt \"MS Shell Dlg 2\";"))
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.EnvironmentaleQTbox = QtGui.QWidget()
        self.EnvironmentaleQTbox.setGeometry(QtCore.QRect(0, 0, 676, 517))
        self.EnvironmentaleQTbox.setObjectName(_fromUtf8("EnvironmentaleQTbox"))
        self.EnvlistFieldsCBox = QtGui.QComboBox(self.EnvironmentaleQTbox)
        self.EnvlistFieldsCBox.setGeometry(QtCore.QRect(88, 62, 421, 22))
        self.EnvlistFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.EnvlistFieldsCBox.setObjectName(_fromUtf8("EnvlistFieldsCBox"))
        self.EnvLbl = QtGui.QLabel(self.EnvironmentaleQTbox)
        self.EnvLbl.setGeometry(QtCore.QRect(9, 9, 51, 16))
        self.EnvLbl.setObjectName(_fromUtf8("EnvLbl"))
        self.EnvMapNameLbl = QtGui.QLabel(self.EnvironmentaleQTbox)
        self.EnvMapNameLbl.setGeometry(QtCore.QRect(69, 8, 431, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.EnvMapNameLbl.setFont(font)
        self.EnvMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.EnvMapNameLbl.setObjectName(_fromUtf8("EnvMapNameLbl"))
        self.EnvTEdit = QtGui.QTextEdit(self.EnvironmentaleQTbox)
        self.EnvTEdit.setGeometry(QtCore.QRect(10, 480, 530, 81))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.EnvTEdit.sizePolicy().hasHeightForWidth())
        self.EnvTEdit.setSizePolicy(sizePolicy)
        self.EnvTEdit.setObjectName(_fromUtf8("EnvTEdit"))
        self.EnvFieldsLbl = QtGui.QLabel(self.EnvironmentaleQTbox)
        self.EnvFieldsLbl.setGeometry(QtCore.QRect(9, 62, 34, 16))
        self.EnvFieldsLbl.setObjectName(_fromUtf8("EnvFieldsLbl"))
        self.SetBtnHelp = QtGui.QPushButton(self.EnvironmentaleQTbox)
        self.SetBtnHelp.setGeometry(QtCore.QRect(560, 510, 102, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetBtnHelp.sizePolicy().hasHeightForWidth())
        self.SetBtnHelp.setSizePolicy(sizePolicy)
        self.SetBtnHelp.setMaximumSize(QtCore.QSize(110, 16777215))
        self.SetBtnHelp.setObjectName(_fromUtf8("SetBtnHelp"))
        self.line_2 = QtGui.QFrame(self.EnvironmentaleQTbox)
        self.line_2.setGeometry(QtCore.QRect(9, 36, 657, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_4 = QtGui.QFrame(self.EnvironmentaleQTbox)
        self.line_4.setGeometry(QtCore.QRect(10, 440, 660, 15))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.EnvTabWidget = QtGui.QTabWidget(self.EnvironmentaleQTbox)
        self.EnvTabWidget.setGeometry(QtCore.QRect(14, 105, 655, 321))
        self.EnvTabWidget.setObjectName(_fromUtf8("EnvTabWidget"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.EnvParameterWidget = QtGui.QTableWidget(self.tab_5)
        self.EnvParameterWidget.setGeometry(QtCore.QRect(10, 21, 630, 141))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvParameterWidget.sizePolicy().hasHeightForWidth())
        self.EnvParameterWidget.setSizePolicy(sizePolicy)
        self.EnvParameterWidget.setAcceptDrops(False)
        self.EnvParameterWidget.setAutoFillBackground(True)
        self.EnvParameterWidget.setDragEnabled(True)
        self.EnvParameterWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.EnvParameterWidget.setShowGrid(True)
        self.EnvParameterWidget.setGridStyle(QtCore.Qt.DotLine)
        self.EnvParameterWidget.setRowCount(0)
        self.EnvParameterWidget.setObjectName(_fromUtf8("EnvParameterWidget"))
        self.EnvParameterWidget.setColumnCount(0)
        self.EnvParameterWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.EnvParameterWidget.verticalHeader().setCascadingSectionResizes(False)
        self.EnvParameterWidget.verticalHeader().setHighlightSections(True)
        self.EnvGetWeightBtn = QtGui.QPushButton(self.tab_5)
        self.EnvGetWeightBtn.setGeometry(QtCore.QRect(540, 190, 104, 24))
        self.EnvGetWeightBtn.setMaximumSize(QtCore.QSize(104, 16777215))
        self.EnvGetWeightBtn.setObjectName(_fromUtf8("EnvGetWeightBtn"))
        self.EnvProgressBar = QtGui.QProgressBar(self.tab_5)
        self.EnvProgressBar.setGeometry(QtCore.QRect(10, 190, 521, 25))
        self.EnvProgressBar.setProperty("value", 0)
        self.EnvProgressBar.setObjectName(_fromUtf8("EnvProgressBar"))
        self.EnvTabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.EnvCalculateBtn = QtGui.QPushButton(self.tab_6)
        self.EnvCalculateBtn.setGeometry(QtCore.QRect(529, 260, 111, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvCalculateBtn.sizePolicy().hasHeightForWidth())
        self.EnvCalculateBtn.setSizePolicy(sizePolicy)
        self.EnvCalculateBtn.setMaximumSize(QtCore.QSize(111, 16777215))
        self.EnvCalculateBtn.setObjectName(_fromUtf8("EnvCalculateBtn"))
        self.EnvTableWidget = QtGui.QTableWidget(self.tab_6)
        self.EnvTableWidget.setEnabled(True)
        self.EnvTableWidget.setGeometry(QtCore.QRect(10, 15, 630, 231))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvTableWidget.sizePolicy().hasHeightForWidth())
        self.EnvTableWidget.setSizePolicy(sizePolicy)
        self.EnvTableWidget.setDragEnabled(True)
        self.EnvTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.EnvTableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.EnvTableWidget.setObjectName(_fromUtf8("EnvTableWidget"))
        self.EnvTableWidget.setColumnCount(0)
        self.EnvTableWidget.setRowCount(0)
        self.EnvTabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.EnvAddFieldBtn = QtGui.QPushButton(self.EnvironmentaleQTbox)
        self.EnvAddFieldBtn.setGeometry(QtCore.QRect(551, 62, 111, 24))
        self.EnvAddFieldBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.EnvAddFieldBtn.setObjectName(_fromUtf8("EnvAddFieldBtn"))
        self.SetBtnAbout = QtGui.QPushButton(self.EnvironmentaleQTbox)
        self.SetBtnAbout.setGeometry(QtCore.QRect(560, 540, 102, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetBtnAbout.sizePolicy().hasHeightForWidth())
        self.SetBtnAbout.setSizePolicy(sizePolicy)
        self.SetBtnAbout.setMaximumSize(QtCore.QSize(110, 16777215))
        self.SetBtnAbout.setObjectName(_fromUtf8("SetBtnAbout"))
        self.SetBtnQuit = QtGui.QPushButton(self.EnvironmentaleQTbox)
        self.SetBtnQuit.setGeometry(QtCore.QRect(560, 480, 102, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetBtnQuit.sizePolicy().hasHeightForWidth())
        self.SetBtnQuit.setSizePolicy(sizePolicy)
        self.SetBtnQuit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.SetBtnQuit.setObjectName(_fromUtf8("SetBtnQuit"))
        self.toolBox.addItem(self.EnvironmentaleQTbox, _fromUtf8(""))
        self.AnalysisQTBox = QtGui.QWidget()
        self.AnalysisQTBox.setGeometry(QtCore.QRect(0, 0, 676, 517))
        self.AnalysisQTBox.setObjectName(_fromUtf8("AnalysisQTBox"))
        self.GraphBtn = QtGui.QPushButton(self.AnalysisQTBox)
        self.GraphBtn.setGeometry(QtCore.QRect(567, 73, 75, 23))
        self.GraphBtn.setObjectName(_fromUtf8("GraphBtn"))
        self.LblGraphic = QtGui.QLabel(self.AnalysisQTBox)
        self.LblGraphic.setGeometry(QtCore.QRect(21, 122, 518, 251))
        self.LblGraphic.setAutoFillBackground(False)
        self.LblGraphic.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LblGraphic.setText(_fromUtf8(""))
        self.LblGraphic.setScaledContents(True)
        self.LblGraphic.setObjectName(_fromUtf8("LblGraphic"))
        self.RenderBtn = QtGui.QPushButton(self.AnalysisQTBox)
        self.RenderBtn.setGeometry(QtCore.QRect(565, 19, 75, 23))
        self.RenderBtn.setObjectName(_fromUtf8("RenderBtn"))
        self.line = QtGui.QFrame(self.AnalysisQTBox)
        self.line.setGeometry(QtCore.QRect(14, 49, 644, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.LabelListFieldsCBox = QtGui.QComboBox(self.AnalysisQTBox)
        self.LabelListFieldsCBox.setGeometry(QtCore.QRect(114, 76, 419, 22))
        self.LabelListFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.LabelListFieldsCBox.setObjectName(_fromUtf8("LabelListFieldsCBox"))
        self.label_3 = QtGui.QLabel(self.AnalysisQTBox)
        self.label_3.setGeometry(QtCore.QRect(29, 78, 64, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.AnlsBtnBox = QtGui.QDialogButtonBox(self.AnalysisQTBox)
        self.AnlsBtnBox.setGeometry(QtCore.QRect(560, 350, 86, 23))
        self.AnlsBtnBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.AnlsBtnBox.setObjectName(_fromUtf8("AnlsBtnBox"))
        self.label_4 = QtGui.QLabel(self.AnalysisQTBox)
        self.label_4.setGeometry(QtCore.QRect(30, 19, 151, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.spinBoxClasNum = QtGui.QSpinBox(self.AnalysisQTBox)
        self.spinBoxClasNum.setGeometry(QtCore.QRect(380, 20, 42, 22))
        self.spinBoxClasNum.setProperty("value", 5)
        self.spinBoxClasNum.setObjectName(_fromUtf8("spinBoxClasNum"))
        self.label_7 = QtGui.QLabel(self.AnalysisQTBox)
        self.label_7.setGeometry(QtCore.QRect(250, 20, 111, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.toolBox.addItem(self.AnalysisQTBox, _fromUtf8(""))
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(1)
        self.EnvTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.EnvAddFieldBtn, self.EnvTEdit)
        Dialog.setTabOrder(self.EnvTEdit, self.GraphBtn)
        Dialog.setTabOrder(self.GraphBtn, self.SetBtnHelp)
        Dialog.setTabOrder(self.SetBtnHelp, self.EnvlistFieldsCBox)
        Dialog.setTabOrder(self.EnvlistFieldsCBox, self.RenderBtn)
        Dialog.setTabOrder(self.RenderBtn, self.LabelListFieldsCBox)
        Dialog.setTabOrder(self.LabelListFieldsCBox, self.AnlsBtnBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "geo Concordance", None))
        self.EnvLbl.setText(_translate("Dialog", "Layer     ", None))
        self.EnvFieldsLbl.setText(_translate("Dialog", "Fields", None))
        self.SetBtnHelp.setText(_translate("Dialog", "Help", None))
        self.EnvGetWeightBtn.setText(_translate("Dialog", "Apply", None))
        self.EnvTabWidget.setTabText(self.EnvTabWidget.indexOf(self.tab_5), _translate("Dialog", "Standard", None))
        self.EnvCalculateBtn.setText(_translate("Dialog", "Calculate weight", None))
        self.EnvTabWidget.setTabText(self.EnvTabWidget.indexOf(self.tab_6), _translate("Dialog", "Advanced", None))
        self.EnvAddFieldBtn.setText(_translate("Dialog", "Add", None))
        self.SetBtnAbout.setText(_translate("Dialog", "About", None))
        self.SetBtnQuit.setText(_translate("Dialog", "Quit", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.EnvironmentaleQTbox), _translate("Dialog", "Criteria", None))
        self.GraphBtn.setText(_translate("Dialog", "Graph", None))
        self.RenderBtn.setText(_translate("Dialog", "Maps", None))
        self.label_3.setText(_translate("Dialog", "Label field", None))
        self.label_4.setText(_translate("Dialog", "Load thematic maps", None))
        self.label_7.setText(_translate("Dialog", "Classes in maps", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.AnalysisQTBox), _translate("Dialog", "Analysis", None))

