# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\geoRSDB.ui'
#
# Created: Wed Aug 20 18:25:16 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(515, 570)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolBox = QtGui.QToolBox(Dialog)
        self.toolBox.setStyleSheet(_fromUtf8("\n"
"font: 75 italic 10pt \"MS Shell Dlg 2\";"))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 497, 462))
        self.page.setObjectName(_fromUtf8("page"))
        self.SettingButtonBox = QtGui.QDialogButtonBox(self.page)
        self.SettingButtonBox.setGeometry(QtCore.QRect(330, 390, 156, 24))
        self.SettingButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.SettingButtonBox.setObjectName(_fromUtf8("SettingButtonBox"))
        self.DiscretizeGbox = QtGui.QGroupBox(self.page)
        self.DiscretizeGbox.setGeometry(QtCore.QRect(10, 30, 471, 131))
        self.DiscretizeGbox.setObjectName(_fromUtf8("DiscretizeGbox"))
        self.ClasseNumDiscSpinBox = QtGui.QSpinBox(self.DiscretizeGbox)
        self.ClasseNumDiscSpinBox.setGeometry(QtCore.QRect(71, 31, 36, 22))
        self.ClasseNumDiscSpinBox.setMaximum(15)
        self.ClasseNumDiscSpinBox.setProperty("value", 6)
        self.ClasseNumDiscSpinBox.setObjectName(_fromUtf8("ClasseNumDiscSpinBox"))
        self.ClassNumbLbl = QtGui.QLabel(self.DiscretizeGbox)
        self.ClassNumbLbl.setGeometry(QtCore.QRect(21, 31, 44, 16))
        self.ClassNumbLbl.setObjectName(_fromUtf8("ClassNumbLbl"))
        self.NewFieldNameDiscLbl = QtGui.QLabel(self.DiscretizeGbox)
        self.NewFieldNameDiscLbl.setGeometry(QtCore.QRect(130, 30, 64, 16))
        self.NewFieldNameDiscLbl.setObjectName(_fromUtf8("NewFieldNameDiscLbl"))
        self.cobBoxFieldNameDisc = QtGui.QComboBox(self.DiscretizeGbox)
        self.cobBoxFieldNameDisc.setGeometry(QtCore.QRect(200, 30, 261, 22))
        self.cobBoxFieldNameDisc.setObjectName(_fromUtf8("cobBoxFieldNameDisc"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.CriteriaQTbox = QtGui.QWidget()
        self.CriteriaQTbox.setGeometry(QtCore.QRect(0, 0, 497, 462))
        self.CriteriaQTbox.setObjectName(_fromUtf8("CriteriaQTbox"))
        self.CritListFieldsCBox = QtGui.QComboBox(self.CriteriaQTbox)
        self.CritListFieldsCBox.setGeometry(QtCore.QRect(100, 33, 181, 20))
        self.CritListFieldsCBox.setObjectName(_fromUtf8("CritListFieldsCBox"))
        self.EnvLbl = QtGui.QLabel(self.CriteriaQTbox)
        self.EnvLbl.setGeometry(QtCore.QRect(2, 0, 71, 19))
        self.EnvLbl.setObjectName(_fromUtf8("EnvLbl"))
        self.CritFieldsLbl = QtGui.QLabel(self.CriteriaQTbox)
        self.CritFieldsLbl.setGeometry(QtCore.QRect(2, 32, 81, 23))
        self.CritFieldsLbl.setObjectName(_fromUtf8("CritFieldsLbl"))
        self.CritMapNameLbl = QtGui.QLabel(self.CriteriaQTbox)
        self.CritMapNameLbl.setGeometry(QtCore.QRect(100, 0, 361, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.CritMapNameLbl.setFont(font)
        self.CritMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.CritMapNameLbl.setObjectName(_fromUtf8("CritMapNameLbl"))
        self.CritTEdit = QtGui.QTextEdit(self.CriteriaQTbox)
        self.CritTEdit.setGeometry(QtCore.QRect(10, 380, 451, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.CritTEdit.sizePolicy().hasHeightForWidth())
        self.CritTEdit.setSizePolicy(sizePolicy)
        self.CritTEdit.setObjectName(_fromUtf8("CritTEdit"))
        self.CritWeighTableWidget = QtGui.QTableWidget(self.CriteriaQTbox)
        self.CritWeighTableWidget.setGeometry(QtCore.QRect(0, 70, 371, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CritWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.CritWeighTableWidget.setSizePolicy(sizePolicy)
        self.CritWeighTableWidget.setDragEnabled(True)
        self.CritWeighTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.CritWeighTableWidget.setAlternatingRowColors(True)
        self.CritWeighTableWidget.setRowCount(0)
        self.CritWeighTableWidget.setObjectName(_fromUtf8("CritWeighTableWidget"))
        self.CritWeighTableWidget.setColumnCount(0)
        self.CritWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.CritWeighTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.CritWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.DeclistFieldsCBox = QtGui.QComboBox(self.CriteriaQTbox)
        self.DeclistFieldsCBox.setGeometry(QtCore.QRect(110, 341, 351, 20))
        self.DeclistFieldsCBox.setObjectName(_fromUtf8("DeclistFieldsCBox"))
        self.DecFieldsLbl = QtGui.QLabel(self.CriteriaQTbox)
        self.DecFieldsLbl.setGeometry(QtCore.QRect(10, 340, 81, 23))
        self.DecFieldsLbl.setObjectName(_fromUtf8("DecFieldsLbl"))
        self.CritRemoveFieldBtn = QtGui.QPushButton(self.CriteriaQTbox)
        self.CritRemoveFieldBtn.setGeometry(QtCore.QRect(390, 30, 75, 24))
        self.CritRemoveFieldBtn.setObjectName(_fromUtf8("CritRemoveFieldBtn"))
        self.CritExtractBtn = QtGui.QPushButton(self.CriteriaQTbox)
        self.CritExtractBtn.setGeometry(QtCore.QRect(390, 80, 75, 201))
        self.CritExtractBtn.setObjectName(_fromUtf8("CritExtractBtn"))
        self.CritHelpBtn = QtGui.QPushButton(self.CriteriaQTbox)
        self.CritHelpBtn.setGeometry(QtCore.QRect(390, 300, 75, 24))
        self.CritHelpBtn.setObjectName(_fromUtf8("CritHelpBtn"))
        self.CritAddFieldBtn = QtGui.QPushButton(self.CriteriaQTbox)
        self.CritAddFieldBtn.setGeometry(QtCore.QRect(300, 30, 75, 24))
        self.CritAddFieldBtn.setObjectName(_fromUtf8("CritAddFieldBtn"))
        self.toolBox.addItem(self.CriteriaQTbox, _fromUtf8(""))
        self.RoulesQTBox = QtGui.QWidget()
        self.RoulesQTBox.setGeometry(QtCore.QRect(0, 0, 497, 462))
        self.RoulesQTBox.setObjectName(_fromUtf8("RoulesQTBox"))
        self.RulesBtnBox = QtGui.QDialogButtonBox(self.RoulesQTBox)
        self.RulesBtnBox.setGeometry(QtCore.QRect(310, 400, 156, 23))
        self.RulesBtnBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.RulesBtnBox.setObjectName(_fromUtf8("RulesBtnBox"))
        self.RulesListWidget = QtGui.QListWidget(self.RoulesQTBox)
        self.RulesListWidget.setGeometry(QtCore.QRect(10, 11, 471, 281))
        self.RulesListWidget.setObjectName(_fromUtf8("RulesListWidget"))
        self.ruleEdit = QtGui.QTextEdit(self.RoulesQTBox)
        self.ruleEdit.setGeometry(QtCore.QRect(10, 310, 471, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.ruleEdit.sizePolicy().hasHeightForWidth())
        self.ruleEdit.setSizePolicy(sizePolicy)
        self.ruleEdit.setObjectName(_fromUtf8("ruleEdit"))
        self.toolBox.addItem(self.RoulesQTBox, _fromUtf8(""))
        self.gridLayout.addWidget(self.toolBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.CritListFieldsCBox, self.CritAddFieldBtn)
        Dialog.setTabOrder(self.CritAddFieldBtn, self.CritRemoveFieldBtn)
        Dialog.setTabOrder(self.CritRemoveFieldBtn, self.CritWeighTableWidget)
        Dialog.setTabOrder(self.CritWeighTableWidget, self.CritExtractBtn)
        Dialog.setTabOrder(self.CritExtractBtn, self.CritHelpBtn)
        Dialog.setTabOrder(self.CritHelpBtn, self.CritTEdit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "geoRules", None))
        self.DiscretizeGbox.setTitle(_translate("Dialog", "Discretize", None))
        self.ClassNumbLbl.setText(_translate("Dialog", "Classes", None))
        self.NewFieldNameDiscLbl.setText(_translate("Dialog", "Field name", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Setting", None))
        self.EnvLbl.setText(_translate("Dialog", "Active layer     ", None))
        self.CritFieldsLbl.setText(_translate("Dialog", "Active field", None))
        self.DecFieldsLbl.setText(_translate("Dialog", "Decision field", None))
        self.CritRemoveFieldBtn.setText(_translate("Dialog", "Remove", None))
        self.CritExtractBtn.setText(_translate("Dialog", " Extract", None))
        self.CritHelpBtn.setText(_translate("Dialog", "Help", None))
        self.CritAddFieldBtn.setText(_translate("Dialog", "Add", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.CriteriaQTbox), _translate("Dialog", "Criteria", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.RoulesQTBox), _translate("Dialog", "Rules", None))

