# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geoWeightedSum.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(689, 577)
        Dialog.setMaximumSize(QtCore.QSize(694, 700))
        font = QtGui.QFont()
        font.setPointSize(6)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(True)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet("\n"
"font: 75 italic 10pt \"MS Shell Dlg 2\";")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.EnvironmentaleQTbox = QtWidgets.QWidget()
        self.EnvironmentaleQTbox.setGeometry(QtCore.QRect(0, 0, 671, 499))
        self.EnvironmentaleQTbox.setObjectName("EnvironmentaleQTbox")
        self.EnvLbl = QtWidgets.QLabel(self.EnvironmentaleQTbox)
        self.EnvLbl.setGeometry(QtCore.QRect(9, 9, 51, 16))
        self.EnvLbl.setObjectName("EnvLbl")
        self.EnvMapNameLbl = QtWidgets.QLabel(self.EnvironmentaleQTbox)
        self.EnvMapNameLbl.setGeometry(QtCore.QRect(69, 8, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.EnvMapNameLbl.setFont(font)
        self.EnvMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.EnvMapNameLbl.setObjectName("EnvMapNameLbl")
        self.EnvTEdit = QtWidgets.QTextEdit(self.EnvironmentaleQTbox)
        self.EnvTEdit.setGeometry(QtCore.QRect(30, 430, 531, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.EnvTEdit.sizePolicy().hasHeightForWidth())
        self.EnvTEdit.setSizePolicy(sizePolicy)
        self.EnvTEdit.setObjectName("EnvTEdit")
        self.SetBtnHelp = QtWidgets.QPushButton(self.EnvironmentaleQTbox)
        self.SetBtnHelp.setGeometry(QtCore.QRect(580, 470, 71, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetBtnHelp.sizePolicy().hasHeightForWidth())
        self.SetBtnHelp.setSizePolicy(sizePolicy)
        self.SetBtnHelp.setMaximumSize(QtCore.QSize(110, 16777215))
        self.SetBtnHelp.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SetBtnHelp.setObjectName("SetBtnHelp")
        self.line_2 = QtWidgets.QFrame(self.EnvironmentaleQTbox)
        self.line_2.setGeometry(QtCore.QRect(9, 36, 657, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.EnvTabWidget = QtWidgets.QTabWidget(self.EnvironmentaleQTbox)
        self.EnvTabWidget.setGeometry(QtCore.QRect(14, 85, 651, 301))
        self.EnvTabWidget.setObjectName("EnvTabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.EnvParameterWidget = QtWidgets.QTableWidget(self.tab_5)
        self.EnvParameterWidget.setGeometry(QtCore.QRect(10, 21, 621, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvParameterWidget.sizePolicy().hasHeightForWidth())
        self.EnvParameterWidget.setSizePolicy(sizePolicy)
        self.EnvParameterWidget.setAcceptDrops(False)
        self.EnvParameterWidget.setAutoFillBackground(True)
        self.EnvParameterWidget.setDragEnabled(True)
        self.EnvParameterWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.EnvParameterWidget.setShowGrid(True)
        self.EnvParameterWidget.setGridStyle(QtCore.Qt.DotLine)
        self.EnvParameterWidget.setRowCount(0)
        self.EnvParameterWidget.setObjectName("EnvParameterWidget")
        self.EnvParameterWidget.setColumnCount(0)
        self.EnvParameterWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.EnvParameterWidget.verticalHeader().setCascadingSectionResizes(False)
        self.EnvParameterWidget.verticalHeader().setHighlightSections(True)
        self.EnvGetWeightBtn = QtWidgets.QPushButton(self.tab_5)
        self.EnvGetWeightBtn.setGeometry(QtCore.QRect(560, 190, 71, 24))
        self.EnvGetWeightBtn.setMaximumSize(QtCore.QSize(104, 16777215))
        self.EnvGetWeightBtn.setObjectName("EnvGetWeightBtn")
        self.EnvProgressBar = QtWidgets.QProgressBar(self.tab_5)
        self.EnvProgressBar.setGeometry(QtCore.QRect(10, 190, 521, 25))
        self.EnvProgressBar.setProperty("value", 0)
        self.EnvProgressBar.setObjectName("EnvProgressBar")
        self.EnvTabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.EnvCalculateBtn = QtWidgets.QPushButton(self.tab_6)
        self.EnvCalculateBtn.setGeometry(QtCore.QRect(520, 240, 111, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvCalculateBtn.sizePolicy().hasHeightForWidth())
        self.EnvCalculateBtn.setSizePolicy(sizePolicy)
        self.EnvCalculateBtn.setMaximumSize(QtCore.QSize(111, 16777215))
        self.EnvCalculateBtn.setObjectName("EnvCalculateBtn")
        self.EnvTableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.EnvTableWidget.setEnabled(True)
        self.EnvTableWidget.setGeometry(QtCore.QRect(10, 15, 621, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvTableWidget.sizePolicy().hasHeightForWidth())
        self.EnvTableWidget.setSizePolicy(sizePolicy)
        self.EnvTableWidget.setDragEnabled(True)
        self.EnvTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.EnvTableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.EnvTableWidget.setObjectName("EnvTableWidget")
        self.EnvTableWidget.setColumnCount(0)
        self.EnvTableWidget.setRowCount(0)
        self.EnvTabWidget.addTab(self.tab_6, "")
        self.SetBtnAbout = QtWidgets.QPushButton(self.EnvironmentaleQTbox)
        self.SetBtnAbout.setGeometry(QtCore.QRect(580, 440, 71, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetBtnAbout.sizePolicy().hasHeightForWidth())
        self.SetBtnAbout.setSizePolicy(sizePolicy)
        self.SetBtnAbout.setMaximumSize(QtCore.QSize(110, 16777215))
        self.SetBtnAbout.setObjectName("SetBtnAbout")
        self.SetBtnQuit = QtWidgets.QDialogButtonBox(self.EnvironmentaleQTbox)
        self.SetBtnQuit.setGeometry(QtCore.QRect(580, 410, 71, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetBtnQuit.sizePolicy().hasHeightForWidth())
        self.SetBtnQuit.setSizePolicy(sizePolicy)
        self.SetBtnQuit.setMaximumSize(QtCore.QSize(101, 16777215))
        self.SetBtnQuit.setAutoFillBackground(True)
        self.SetBtnQuit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.SetBtnQuit.setObjectName("SetBtnQuit")
        self.toolBox.addItem(self.EnvironmentaleQTbox, "")
        self.AnalysisQTBox = QtWidgets.QWidget()
        self.AnalysisQTBox.setGeometry(QtCore.QRect(0, 0, 671, 499))
        self.AnalysisQTBox.setObjectName("AnalysisQTBox")
        self.AnlsBtnQuit = QtWidgets.QDialogButtonBox(self.AnalysisQTBox)
        self.AnlsBtnQuit.setGeometry(QtCore.QRect(560, 460, 86, 23))
        self.AnlsBtnQuit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.AnlsBtnQuit.setObjectName("AnlsBtnQuit")
        self.RenderBtn_2 = QtWidgets.QPushButton(self.AnalysisQTBox)
        self.RenderBtn_2.setGeometry(QtCore.QRect(820, 470, 90, 24))
        self.RenderBtn_2.setObjectName("RenderBtn_2")
        self.AnsytBtnAbout = QtWidgets.QPushButton(self.AnalysisQTBox)
        self.AnsytBtnAbout.setGeometry(QtCore.QRect(440, 460, 71, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnsytBtnAbout.sizePolicy().hasHeightForWidth())
        self.AnsytBtnAbout.setSizePolicy(sizePolicy)
        self.AnsytBtnAbout.setMaximumSize(QtCore.QSize(110, 16777215))
        self.AnsytBtnAbout.setObjectName("AnsytBtnAbout")
        self.groupBox = QtWidgets.QGroupBox(self.AnalysisQTBox)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 641, 161))
        self.groupBox.setObjectName("groupBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(205, 51, 111, 20))
        self.label_7.setObjectName("label_7")
        self.spinBoxClasNum = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxClasNum.setGeometry(QtCore.QRect(335, 51, 42, 22))
        self.spinBoxClasNum.setProperty("value", 5)
        self.spinBoxClasNum.setObjectName("spinBoxClasNum")
        self.RenderBtn = QtWidgets.QPushButton(self.groupBox)
        self.RenderBtn.setGeometry(QtCore.QRect(500, 50, 95, 23))
        self.RenderBtn.setObjectName("RenderBtn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.AnalysisQTBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 180, 641, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(110, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.LabelListFieldsCBox = QtWidgets.QComboBox(self.groupBox_2)
        self.LabelListFieldsCBox.setGeometry(QtCore.QRect(210, 90, 69, 22))
        self.LabelListFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.LabelListFieldsCBox.setSizeIncrement(QtCore.QSize(20, 0))
        self.LabelListFieldsCBox.setBaseSize(QtCore.QSize(4, 0))
        self.LabelListFieldsCBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.LabelListFieldsCBox.setFrame(True)
        self.LabelListFieldsCBox.setObjectName("LabelListFieldsCBox")
        self.GraphBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.GraphBtn.setGeometry(QtCore.QRect(500, 90, 95, 24))
        self.GraphBtn.setObjectName("GraphBtn")
        self.toolBox.addItem(self.AnalysisQTBox, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        self.EnvTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.EnvTEdit, self.SetBtnHelp)
        Dialog.setTabOrder(self.SetBtnHelp, self.AnlsBtnQuit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "geo Weighted Sum"))
        self.EnvLbl.setText(_translate("Dialog", "Layer     "))
        self.SetBtnHelp.setText(_translate("Dialog", "Help"))
        self.EnvGetWeightBtn.setText(_translate("Dialog", "Apply"))
        self.EnvTabWidget.setTabText(self.EnvTabWidget.indexOf(self.tab_5), _translate("Dialog", "Standard"))
        self.EnvCalculateBtn.setText(_translate("Dialog", "Calculate weight"))
        self.EnvTabWidget.setTabText(self.EnvTabWidget.indexOf(self.tab_6), _translate("Dialog", "Standard"))
        self.EnvTabWidget.setTabToolTip(self.EnvTabWidget.indexOf(self.tab_6), _translate("Dialog", "<html><head/><body><p>colun vs row</p><p><br/></p></body></html>"))
        self.SetBtnAbout.setText(_translate("Dialog", "About"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.EnvironmentaleQTbox), _translate("Dialog", "Criteria"))
        self.RenderBtn_2.setText(_translate("Dialog", "Load maps"))
        self.AnsytBtnAbout.setText(_translate("Dialog", "About"))
        self.groupBox.setTitle(_translate("Dialog", "Load thematic maps"))
        self.label_7.setText(_translate("Dialog", "Classes in maps"))
        self.RenderBtn.setText(_translate("Dialog", "Load maps"))
        self.groupBox_2.setTitle(_translate("Dialog", "Buld charts"))
        self.label_3.setText(_translate("Dialog", "Label field"))
        self.GraphBtn.setText(_translate("Dialog", "Load charts"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.AnalysisQTBox), _translate("Dialog", "Analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

